export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const POST_TASK_COMPLETE = 'TASK_POST_COMPLETE';
export const POST_TASK_SUCCESS = 'TASK_POST_SUCCESS';
export const POST_TASK_FAIL = 'TASK_POST_FAIL';
export const POST_TASK_START = 'TASK_POST_START';

export const FETCH_TASKS_COMPLETE = 'FETCH_TASKS_COMPLETE';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL';
export const FETCH_TASKS_START = 'FETCH_TASKS_START';

export const SET_TODAY = 'SET_TODAY';
